# Generated by Django 3.0.2 on 2020-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
