# Generated by Django 3.0.2 on 2020-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200420_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
