# Generated by Django 3.0.2 on 2020-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagement', '0002_auto_20200420_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
